name: Debug workflows
run-name: Debug status check functions

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  status-1:
    name: status check workflow 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run command error
        id: cmd
        run: |
          type -a gh

      - name: Debug if previous step fails
        if: ${{ steps.cmd.conclusion == 'success' }}
        run: echo "FAIL"

      - name: Failing step
        id: demo
        run: exit 0

      - name: The demo step has failed
        if: ${{ steps.demo.conclusion == 'failure' }}
        run: echo "Debug demo step"

      - name: run.sh
        run: ./caller.sh

      - name: debug run.sh env
        run: |
          echo ${{ env.SCRIPT }}

  status-2:
    name: status check workflow 2
    needs: status-1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
          cache: false