name: Debug workflows
run-name: Debug GitHub self-hosted runner
on:
  workflow_dispatch:
    inputs:
      run:
        description: Run the workflow
        required: false
        type: boolean
        default: false

defaults:
  run:
    shell: bash

jobs:
  run-workflow:
    name: RUN WORKFLOW
    runs-on:
      - self-hosted
      - ancillaries
      - actions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - NodeJS v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Debug - Packer latest version
        uses: hashicorp/setup-packer@main
        with:
          version: latest

      - name: Debug - Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
