name: Debug workflows in EKS
run-name: Debug GitHub Actions Runner Controller
on:
  workflow_dispatch:
    inputs:
      run:
        description: Run the workflow
        required: true
        type: boolean
        default: true

defaults:
  run:
    shell: bash

jobs:
  run-workflow-1:
    strategy:
      max-parallel: 2
      matrix:
        java-version: [16, 17, 21]
    name: ARC WORKFLOW 1
    runs-on: runner-set

    steps:
      - uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin

  run-workflow-2:
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    name: ARC WORKFLOW 2
    runs-on: runner-set

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
          cache: false